using System.Collections;
using System.Collections.Generic;
using UnityEngine;



public class PlanetData : MonoBehaviour {

	/*
	PLANET DATA

	--Storage class for our data so it can be accessed by other functions during gameplay.
	--Not to be manually set -- should be generated by PlanetManager.cs
	--Contains an "update" function to be called after data has been loaded.

	*/

	MeshRenderer meshRenderer;

	public string planetName;
	public bool minimapVisible;
	public int minimapSize;
	public string graphic;

	void Awake() {
		meshRenderer = GetComponent<MeshRenderer>();
	}


	public void UpdatePlanetDisplay() {
		this.name = planetName;
		this.meshRenderer.material = Resources.Load("Visuals/Planets/" + graphic, typeof(Material)) as Material;
		//Evidently there's no clean way to set material except by manually finding it in Resources
	}

}
